### ISSUE TITLE
Thanks for JSON File

### ISSUE THREAD

**Issue by tderflinger** [sigpwned/iso-15924-and-unicode-scripts#1]
Hi there,

I just wanted to say thanks for your useful JSON file. I extended your file a bit with my project "Script Language Matcher" which matches all scripts to their respective language: https://github.com/tderflinger/script-lang-matcher .
Maybe also useful for you.

Best regards,
-Thomas

**Comment by sigpwned** [comment]
Sorry it took me a minute to see this! I'm very glad you found it useful! Appreciate the "hello." 😄
